### ISSUE TITLE
adding references

### ISSUE THREAD

**Issue by ozanj** [ozanj/cerpp_2020#4]
can you remind me how to add new references to presentation [e.g., stevens and other 2016]; I am following the code of previous references but doesn't seem to add the reference

**Comment by cyouh95** [comment]
Is it for [this line](https://github.com/ozanj/cerpp_2020/blob/9651c0e3975c0728781a01365de71b4ee901245e/index.Rmd#L175)? I think you might just be missing the `` `r `` part in the front. This seems to work for me: `` `r citep(bib['RN4517'])` ``

**Comment by ozanj** [comment]
looks good!
