### ISSUE TITLE
iron triangle image

### ISSUE THREAD

**Issue by ozanj** [ozanj/cerpp_2020#5]
I added "iron triangle" image to second slide of conceptual framework

this slide has two columns, with iron triangle image on left colum.

can you change the iron triangle image so that the triangle is taller; essentially make it an isosceles triangle w/ the tuition and academiq quality legs longer than the "access" base

**Comment by cyouh95** [comment]
Updated the image!

I didn't change `index.Rmd` in case you were in the middle of editing anything, but maybe we can also add some more space above the image [here](https://github.com/ozanj/cerpp_2020/blob/9651c0e3975c0728781a01365de71b4ee901245e/index.Rmd#L194):
```
<img src="assets/images/iron_triangle.png" alt="Iron Triangle" style="width:80%;float:left;padding-top:30px;">
```

**Comment by ozanj** [comment]
Thanks!
